spring:
  application:
    name: kafka-opensearch-consumer




kafka:
  custom:
    bootstrap-servers: ${KAFKA_CUSTOM_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      raw:
        topic: ${KAFKA_CUSTOM_CONSUMER_RAW_TOPIC:raw-rates}
      calc:
        topic: ${KAFKA_CUSTOM_CONSUMER_CALC_TOPIC:calculated-rates}
      auto-offset-reset: ${KAFKA_CUSTOM_CONSUMER_AUTO_OFFSET_RESET:earliest}
      group-id: ${KAFKA_CUSTOM_CONSUMER_GROUP-ID:opensearch-group}