version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - forex-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - forex-net


  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper
    networks:
      - forex-net

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafka-ui
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    networks:
      - forex-net
    depends_on:
      - kafka

  tcp-data-provider:
    image: yusufokr0/tcp-forex-data-provider
    container_name: tcp_data_provider_app
    ports:
      - "8090:8090"
    environment:
      - CURRENCY_PAIRS=TCP_USDTRY,TCP_EURUSD,TCP_GBPUSD
      - TCP_USDTRY_BID=37.9973
      - TCP_USDTRY_ASK=38.0333
      - TCP_USDTRY_MIN_LIMIT=35.2134
      - TCP_USDTRY_MAX_LIMIT=40.1324
      - TCP_EURUSD_BID=1.0848
      - TCP_EURUSD_ASK=1.0949
      - TCP_EURUSD_MIN_LIMIT=1.01254
      - TCP_EURUSD_MAX_LIMIT=1.21423
      - TCP_GBPUSD_BID=1.295
      - TCP_GBPUSD_ASK=1.395
      - TCP_GBPUSD_MIN_LIMIT=1.11245
      - TCP_GBPUSD_MAX_LIMIT=1.42142
      - PUBLISH_FREQUENCY=10000
      - USER_CREDENTIALS=user|pass,admin|admin
      - SPIKE_INTERVAL=10
    networks:
      - forex-net

networks:
  forex-net:
    driver: bridge