version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - forex-net
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres-kafka:
    image: postgres
    container_name: kafka-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: forex_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - forex-net
    volumes:
      - postgres-data-collector:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres-rest-platform:
    image: postgres
    container_name: rest-platform-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: rest_platform_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - forex-net
    volumes:
      - postgres-rest-provider:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s




  forex-data-collector:
    image: yusufokr0/forex-data-collector
    container_name: forex-data-collector
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SUBSCRIBERS_CONFIG_PATH: /app/conf/subscribers.json
    volumes:
      - main-app-log:/app/forex-data-collector/logs
      - ./external-config/main-app/subscribers.json:/app/conf/subscribers.json:ro
    networks:
      - forex-net
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      tcp-data-provider:
        condition: service_started
      rest-data-provider:
        condition: service_started



  tcp-data-provider:
    image: yusufokr0/tcp-data-provider
    container_name: tcp-platform
    ports:
      - "8090:8090"
    volumes:
      - tcp-platform-log:/app/tcp-data-provider/logs
    networks:
      - forex-net


  rest-data-provider:
    image: yusufokr0/rest-data-provider
    container_name: rest-platform
    ports:
      - "8092:8092"
    environment:
      DATABASE_URL: jdbc:postgresql://rest-platform-db:5432/rest_platform_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      REDIS_CUSTOM_HOST: redis
      REDIS_CUSTOM_PORT: 6379
    volumes:
      - rest-platform-log:/app/rest-data-provider/logs
    networks:
      - forex-net
    depends_on:
      postgres-rest-platform:
        condition: service_healthy
      redis:
        condition: service_healthy



  kafka-db-consumer:
    image: yusufokr0/kafka-db-consumer
    container_name: kafka-db-consumer
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-kafka:5432/forex_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      KAFKA_CUSTOM_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - forex-net
    depends_on:
      kafka:
        condition: service_healthy
      postgres-kafka:
        condition: service_healthy



  kafka-opensearch-consumer:
    image: yusufokr0/kafka-opensearch-consumer
    container_name: kafka-opensearch-consumer
    environment:
      KAFKA_CUSTOM_BOOTSTRAP_SERVERS: kafka:29092
      OPENSEARCH_HOST: opensearch
      OPENSEARCH_PORT: 9200
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: Yusuf.32Bits
    networks:
      - forex-net
    depends_on:
      kafka:
        condition: service_healthy
      opensearch:
        condition: service_healthy



  ######## KAFKA COMPONENTS ########

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-log:/var/lib/zookeeper/log
    networks:
      - forex-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - forex-net
    depends_on:
      zookeeper:
        condition: service_started
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:29092", "--list"]
      interval: 20s
      timeout: 10s
      retries: 3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: forex-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - forex-net
    depends_on:
      kafka:
        condition: service_healthy




  ######## LOG PIPELINE ########


  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.12.1
    container_name: filebeat
    entrypoint: "filebeat -e -strict.perms=false"   # bypass config file permission check.
    user: root
    volumes:
      - ./forex-data-collector/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - main-app-log:/var/log/main-app:ro  # only readable
    networks:
      - forex-net
    depends_on:
      logstash:
        condition: service_started
      forex-data-collector:
        condition: service_started



  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
    container_name: logstash
    user: root
    ports:
      - "5044:5044"
    volumes:
      - ./forex-data-collector/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - forex-net
    depends_on:
      opensearch:
        condition: service_healthy

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    ports:
      - "9200:9200" # OpenSearch API
      - "9600:9600" # Performans izleme
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Yusuf.32Bits
    networks:
      - forex-net
    healthcheck:
      test: [ "CMD", "curl", "-k", "-u", "admin:Yusuf.32Bits", "-f", "https://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 10s
      retries: 6

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601" # OpenSearch Dashboards web arayüzü
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      - SERVER_HOST=0.0.0.0
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Yusuf.32Bits
    networks:
      - forex-net
    depends_on:
      opensearch:
        condition: service_healthy


volumes:
  redis-data:
  zk-data:
  zk-log:
  kafka-data:
  postgres-data-collector:
  postgres-rest-provider:
  rest-platform-log:
  tcp-platform-log:
  main-app-log:

networks:
  forex-net:
    driver: bridge
