spring:
  application:
    name: kafkadbconsumer
  datasource:
    url: jdbc:postgresql://localhost:5432/forex_db
    username: postgres
    password: 5591564
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


kafka:
  custom:
    bootstrap-servers: localhost:9092
    consumer:
      raw:
        topic: raw-rates
        group-id: raw-rates-group
      calculated:
        topic: calculated-rates
        group-id: calculated-rates-group
      auto-offset-reset: latest

