rest:
  rates:
    usdtry:
      bid: 38.4426
      ask: 38.8584
      min-limit: 36.5134
      max-limit: 40.1324
    eurusd:
      bid: 1.1266
      ask: 1.1569
      min-limit: 1.02254
      max-limit: 1.22423
    gbpusd:
      bid: 1.3273
      ask: 1.3573
      min-limit: 1.22245
      max-limit: 1.42142
