rest:
  rates:
    rest_usdtry:
      bid: 38.4426
      ask: 38.8584
      min-limit: 37.9134
      max-limit: 39.1324
    rest_eurusd:
      bid: 1.1266
      ask: 1.1369
      min-limit: 1.10654
      max-limit: 1.14654
    rest_gbpusd:
      bid: 1.3273
      ask: 1.3573
      min-limit: 1.30245
      max-limit: 1.34142
